### ISSUE TITLE
您好，复现您的代码出现各种问题（目录等），不知道是否代码不是最新的，请问能提供一下可以运行的代码么？

### ISSUE THREAD

**Issue by wisediag** [xubodhu/MAF#2]

**Comment by JinFish** [comment]
您好，运行该代码之前需要先下载对应数据，并且搭建对应运行环境。我猜测，您可能在数据集和运行环境方面存在问题，请问您可以提供具体的报错信息吗？

**Comment by fmdmm** [comment]
十分感谢您的回复！ 之前是看到代码掉包类似“from my_bert.file_utils import”，实际上文件是mybert，以及雀氏是环境有点问题，就以为是不是最新代码，现在已经可以运行啦！再次感谢！

**Comment by wisediag** [comment]
十分感谢您的回复！ 之前是看到代码掉包类似“from my_bert.file_utils import”，实际上文件是mybert，以及雀氏是环境有点问题，就以为是不是最新代码，现在已经可以运行啦！再次感谢！

还想问您一下，关于“Cross-Modal Alignment Module (CA)”部分的代码，应该就是total_loss这个函数里面去计算其loss的，但是对于初始值 “temp=0.179, temp_lamb=0.7,lamb=0.62”是到哪里得到的啊？

**Comment by JinFish** [comment]
您好，以上参数是通过网格搜索获得的。
